config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resource :session, only: [:new, :create, :destroy]
  resource :setting, only: [:show, :update]

  resources :artists, only: [:index, :show]
  resources :stream, only: [:new]
  resources :transcoded_stream, only: [:new]
  resources :songs, only: [:index, :show]
  resources :albums, only: [:index, :show]

  resources :users, except: [:show] do
    resource :settings, only: [:update]
  end

  resources :playlists, except: [:show, :new, :edit] do
    resource :songs, only: [:show, :create, :destroy], module: 'playlists'
  end

  namespace :current_playlist do
    resource :songs, only: [:show, :update, :create, :destroy]
  end

  namespace :favorite_playlist do
    resource :songs, only: [:show, :create, :destroy]
  end

  namespace :dialog do
    resources :playlists, only: [:index]
  end

  get '/403', to: 'errors#forbidden', as: :forbidden
  get '/404', to: 'errors#not_found', as: :not_found
  get '/422', to: 'errors#unprocessable_entity', as: :unprocessable_entity
  get '/500', to: 'errors#internal_server_error', as: :internal_server_error
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, uniqueness: { scope: :artist }

  has_many :songs, -> { order(:tracknum) }, dependent: :destroy
  belongs_to :artist, touch: true

  def title
    is_unknown? ? I18n.t('text.unknown_album') : name
  end

  def has_image?
    image.file.present?
  end

  def is_unknown?
    name.blank?
  end

  def need_attach_from_discogs?
    Setting.discogs_token.present? && !has_image? && !is_unknown?
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  include Pagy::Backend

  before_action :require_login
  before_action :find_album, except: [:index]

  def index
    records = Album.includes(:artist).order(:name)
    @pagy, @albums = pagy_countless(records)
  end

  private

    def find_album
      @album = Album.find(params[:id])
    end
end

app/views/albums/_album.html.erb
<div class='cards__item'>
  <%= link_to album_path(album) do %>
    <%= image_tag image_url_for(album), class: 'image' %>
  <% end %>
  <div class='cards__item__body'>
    <%= link_to album.title, album_path(album), class: 'cards__item__title text-truncate' %>
    <p class='cards__item__text text-truncate'><%= album.artist.title %></p>
  </div>
</div>

app/views/albums/index.html.erb
<% if @albums.empty? %>
  <%= empty_alert_tag has_icon: true %>
<% else %>
  <div data-controller='infinite-scroll' data-infinite-scroll-next-url='<%= pagy_next_url(@pagy) %>'>
    <div class='cards' id='js-albums-content'>
      <%= render partial: 'album', collection: @albums, cached: true %>
    </div>
    <div data-target='infinite-scroll.trigger' class='display__justify-align-center'>
      <% if @pagy.next %>
        <%= loader_tag %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/albums/index.js.erb
App.appedNextPageContentTo('#js-albums-content', '<%= j(render partial: 'album', collection: @albums, cached: true) %>', '<%= pagy_next_url(@pagy) %>')

app/views/albums/show.html.erb
<% cache @album do %>
  <div class='display__medium-width' data-controller='playlist-songs'>
    <div class='heading heading--expand'>
      <div class='heading__image'>
        <%= image_tag image_url_for(@album), class: 'image' %>
      </div>
      <div class='heading__body'>
        <div class='heading__body__text heading__body__text--main'><%= @album.title %></div>
        <div class='heading__body__text'><%= @album.artist.title %></div>
        <div class='heading__body__text'>
          <span><%= @songs.load.size %> <%= t('label.tracks') %></span>
          <span>,</span>
          <span class='monospace-font'><%= format_duration(@songs.sum(:length)) %></span>
        </div>
        <div class='heading__body__actions'>
          <%= link_to t('label.play_all'), current_playlist_songs_path(song_ids: @album.song_ids ), method: :put, remote: true, class: 'button button--primary' %>
        </div>
      </div>
    </div>
    <ul class='list list--dark-border' data-action='click->playlist-songs#actionHandler'>
      <% @songs.each do |song| %>
        <li class='list__item pointer-cursor' data-target='playlist-songs.item' data-song-id='<%= song.id %>' data-playlist-songs-action='play'>
          <span class='list__item__content'>
            <span class='list__item__info list__item__info--main'><%= song.name %></span>
          </span>
          <span class='list__item__content list__item__content--minor'>
            <span class='list__item__info list__item__info--action' data-playlist-songs-action='showPlaylistsDialog'>
              <%= icon_tag 'playlist-add', size: 'small', title: t('text.add_to_playlist') %>
            </span>
            <span class='list__item__info list__item__info--minor monospace-font'><%= format_duration(song.length) %></span>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>